### ISSUE TITLE
Problem in running the tutorial on discovery

### ISSUE THREAD

**Issue by CC90** [francxx96/declare4py#3]
Hi all, I am trying to run the tutorial notebook for discovery. When trying to compute the itemsets, I get the following error:
  File "/usr/local/lib/python3.11/site-packages/declare4py/declare4py.py", line 85, in activities_log_projection
    tmp_trace.append(event["concept:name"])
                     ~~~~~^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Does the python notebook run on your end? Any help would be much appreciated.
Best regards

**Comment by ivanDonadello** [comment]
I am sorry for this late reply. This version of Declare4Py is no longer supported, please use the new version here https://github.com/ivanDonadello/Declare4Py
